### ISSUE TITLE
Incorrect default expression for database URL

### ISSUE THREAD

**Issue by jbrucker** [colarrbear/ku-polls#26]
https://github.com/colarrbear/ku-polls/blob/d0d022ca5f004340489180eaa8463c8f1eae9de3/mysite/settings.py#L82-L85

This does not create a database in your ku-polls directory.
The string expression for default=... URL is incorrect.
Print it on the console and you will see.

This is **2 configuration errors** in the same code (one in sample.env and one here).   
Did you test your code?

Clone a new copy of your Github repo into a different location
and see if it works.

**Comment by colarrbear** [comment]
I've updated. The new configuration is as follows:

```DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}```
